List<Map<String, dynamic>> anggotaList = [
  {'nama': 'Dinata Lastie', 'kelas': 'VII E', 'foto': 'assets/profil/dinatalastie.png', 'pengikut': false},
  {'nama': 'Sia Latifa Rahmawati', 'kelas': 'VIII E', 'foto': 'assets/profil/sialatifarahmawati.png', 'pengikut': false},
  {'nama': 'Gavin Santana', 'kelas': 'VIII I', 'foto': 'assets/profil/gavinsantana.png', 'pengikut': true},
  {'nama': 'Lidya Esandry', 'kelas': 'VIII E', 'foto': 'assets/profil/lidyaesandry.png', 'pengikut': false},
  {'nama': 'Cassius Renno', 'kelas': 'VII F', 'foto': 'assets/profil/cassiusreno.png', 'pengikut': false},
  {'nama': 'Bhaskara Hadrian Athala', 'kelas': 'VII C', 'foto': 'assets/profil/bhaskarahadrianathala.png', 'pengikut': false},
  {'nama': 'Agatha Luisa Arsyila', 'kelas': 'IX G', 'foto': 'assets/profil/agathaluisaarsyla.png', 'pengikut': false},
  {'nama': 'Exa Winandya', 'kelas': 'VIII A', 'foto': 'assets/profil/exawinandya.png', 'pengikut': false},
  {'nama': 'Azzam Pranata', 'kelas': 'VII E', 'foto': 'assets/profil/dinatalastie.png', 'pengikut': false},
  {'nama': 'Nayla Ramadhani', 'kelas': 'VIII E', 'foto': 'assets/profil/sialatifarahmawati.png', 'pengikut': false},
  {'nama': 'Farel Nugraha', 'kelas': 'VIII I', 'foto': 'assets/profil/gavinsantana.png', 'pengikut': false},
  {'nama': 'Zahira Putri', 'kelas': 'VIII E', 'foto': 'assets/profil/lidyaesandry.png', 'pengikut': false},
  {'nama': 'Dimas Wibowo', 'kelas': 'VII F', 'foto': 'assets/profil/cassiusreno.png', 'pengikut': false},
  {'nama': 'Keysha Anindya', 'kelas': 'VII C', 'foto': 'assets/profil/bhaskarahadrianathala.png', 'pengikut': false},
  {'nama': 'Aldi Saputra', 'kelas': 'IX G', 'foto': 'assets/profil/agathaluisaarsyla.png', 'pengikut': false},
  {'nama': 'Salma Fauziah', 'kelas': 'VIII A', 'foto': 'assets/profil/exawinandya.png', 'pengikut': false},
  {'nama': 'Rehan Mahendra', 'kelas': 'VII E', 'foto': 'assets/profil/dinatalastie.png', 'pengikut': false},
  {'nama': 'Tiara Meisya', 'kelas': 'VIII E', 'foto': 'assets/profil/sialatifarahmawati.png', 'pengikut': false},
  {'nama': 'Farhan Rizky', 'kelas': 'VIII I', 'foto': 'assets/profil/gavinsantana.png', 'pengikut': false},
  {'nama': 'Aulia Rahma', 'kelas': 'VIII E', 'foto': 'assets/profil/lidyaesandry.png', 'pengikut': false},
  {'nama': 'Ilham Satria', 'kelas': 'VII F', 'foto': 'assets/profil/cassiusreno.png', 'pengikut': false},
  {'nama': 'Salsabila Dewi', 'kelas': 'VII C', 'foto': 'assets/profil/bhaskarahadrianathala.png', 'pengikut': false},
  {'nama': 'Arga Prasetyo', 'kelas': 'IX G', 'foto': 'assets/profil/agathaluisaarsyla.png', 'pengikut': false},
];